Fix failures on Fedora.
Install rubygem-json RPM package in Fedora container as it is used in rake.

```
LoadError: cannot load such file -- json
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/formatter/json_formatter.rb:3:in `require'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/formatter/json_formatter.rb:3:in `<top (required)>'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop.rb:524:in `require'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop.rb:524:in `<top (required)>'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/rake_task.rb:44:in `require'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/rake_task.rb:44:in `run_cli'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/rake_task.rb:36:in `run_main_task'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/build/vendor/bundle/ruby/3.0.0/gems/rubocop-0.50.0/lib/rubocop/rake_task.rb:26:in `block in initialize'
/build/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
```